spring.application.name=citas

server.port=8085
spring.application.name=servicio-citas

# Base de datos independiente para Citas
spring.datasource.url=jdbc:mysql://localhost:3306/db_veterinaria_citas?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactivamos Eureka temporalmente para que no te tire el error rojo al apagarlo
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false